### ISSUE TITLE
Mintend noun modal show incorrect noun image & id

### ISSUE THREAD

**Issue by nikitattt** [fomo-nouns/fomo-nouns#10]
# Bug:

After noun minting, the informational modal sometimes shows the previous noun id, and *maybe* image of the noun derived from the id of the previous noun.

## Examples:
*Should be noun 326, showed 325:*
![image](https://user-images.githubusercontent.com/53146405/171245285-349a010e-0735-42c7-9799-44dde10937a8.png)

*Should be noun 319, showed 318(left image):*
![image](https://user-images.githubusercontent.com/53146405/171245591-e6cdf10a-cd06-4341-bf44-228fefc182a7.png)

## Observed in browsers:
chrome v100.0.4896.127 (arm64)

![image](https://user-images.githubusercontent.com/53146405/171252602-e28c2726-06fd-4699-80f5-f3b5c776815f.png)

### Comment from solimander:

> seems like a race condition. sometimes setNextNounId increments the noun id in time to show the correct noun image and id in the modal, and sometimes it does not

**Comment by theforager** [comment]
Thanks @nikitattt! Awesome to have this logged as an issue. I've observed some weirdness on this too.

Will look into this someday soon.
